# All units in milliseconds unless otherwise specified
# CPI = Cognitive Performance Index - A score from 0-100
# BRD = Blocking Round Duration - Average time (in ms) between two blocks
# ART = Average Response Time - Average response time of n answers


practice_mode:
    no_response_duration: 8000
    max_right_count: 5
    right_count_art_less_than: 2600  # The correct count must have an art under 2600ms

    total_answer_count: 20  # Number of answers (unsuccessful) under `max_correct_duration` to end the test in practice-test mode

self_paced:
    no_response_duration: 3000  # No response time before the answer is displayed as incorrect
    number_of_training_rounds: 1  # Number of rounds at the start to get the user used to the test
    
    max_right_count: 5  # Number of right answers *in a row* before machine paced starts
    max_wrong_count: 5  # Number of wrong answers in a row to end the test
    right_count_art_less_than: 2600  # The correct count must have an art under 2600ms
    
    total_answer_count: 20  # Number of answers (unsuccessful) under `max_correct_duration` to end the test in self-paced mode

machine_paced:
    max_start_duration: 2600  # Maximum initial `duration` (ignoring `self_paced_average`)
    initial_speedup_amount: 100  # Amount to speed up by at the start of machine-paced

    minimum_response_time: 600  # Theoretical minimum response time

    rolling_average:
        mean_size: 8  # Take the correct answers of the last `mean_size` rounds
        # The percentage of the last `mean_size` answers that must be correct
        threshold: 0.7  # Otherwise the test enters self paced restart round

    blocking:
        no_input_count: 2  # How many rounds with no response to declare a "block"

        slow_down_duration: 450  # After blocking, resume with `machine_pace` + this amount
        duration_delta: 250  # For the test to end, two blocks must occur within this range

        min_correct_answers: 2  # Number of correct answers in a row needed to continue with MP
        max_wrong_answers: 3  # Number of total wrong answers before the test ends

        no_response_duration: 6000  # No response time before the test ends

        max_block_count:  8 # Maximum number of blocks allowed before the test fails

    # The test slows down when the user gets less than `rolling_average.threshold` correct answers 
    incorrect:
        base_duration: 50  # When slowing down, decrease `duration` by this amount

    # The test speeds up when the user gets more than `rolling_average.threshold` correct answers
    correct:
        # The formula for correct answers is
        #  (`x` * ratio - `y`) * roundDuration
        x: 0.1  # Used in the correct formula
        y: 0.14 # Used in the correct formula
        
        max_speedup_amount: 200  # Maximum speedup amount
        # Maximum slowdown amount
        max_slowdown_amount: 10  # This can occur in the case of an answer correct from the previous round

anti_spoofing:
    max_bad_tests_in_session: 6 # Number of bad tests because retest is no longer an option

timeouts:
    max_initial_no_response: 30_000  # Initial starting time before the test ends if no response is given
    max_test_duration: 150_000  # Maximum time before the test ends
    
cpi_calculation:
    cpi_min: 0  # Lower bound
    cpi_max: 100  # Upper bound
    brd_min: 700  # Theoretical number where cpi should be 100
    brd_max: 1800  # Theoretical number where cpi should be 0

exit_codes:
    0:
        status: "success"
        message: "Test completed successfully"
    1:
        status: "failed"
        message: "No response from the user, timed out"
    2: 
        status: "failed"
        message: "Could not respond correctly"
    3:
        status: "failed"
        message: "Too many blocks"
    4:
        status: "failed"
        message: "Does not know test well enough to continue"
    

# Whether to save round data and have the ability for the user to download it - 
save_round_data: true  # Or to automatically send it to another user

number_of_endmode_rounds: 2  # Number of extra rounds at the end of the test

error: False  # An error variable that is set to True if there is a version error

display_refresher_screens: true  # Whether or not to display the 6-7 refresher screens
