# All units in milliseconds unless otherwise specified
# CPI = Cognitive Performance Index - A score from 0-100
# BRD = Blocking Round Duration - Average time (in ms) between two blocks

self_paced:
    no_response_duration: 6000  # No response time before the test ends
    number_of_training_rounds: 1  # Number of rounds at the start to get the user used to the test
    max_wrong_count: 5  # Number of wrong answers before the test ends
    max_right_count: 4  # Number of right answers *in a row* before machine paced starts
    total_correct_count: 12  # Number of correct answers under `max_correct_duration` to end the test
    max_correct_duration: 3000  # Answers under this time are counted

machine_paced:
    max_count: 8  # ?
    max_start_duration: 2400  # Maximum initital `duration` (ignoring `self_paced_average`)
    not_there: 0  # ?
    not_there_disabled: true  # ?

    minimum_response_time: 600  # Theoretical minimum response time

    rolling_average:
        mean_size: 8  # Take the correct answers of the last `mean_size` rounds
        threshold: 0.7  # Percentage of correct answers before speeding up / slowing down

        max_wrong_count: 5  # Number of wrong answers before the test ends

    blocking:
        no_input_count: 2  # How many rounds with no response to declare a "block"

        slow_down_duration: 375  # After blocking, resume with `machine_pace` + this amount
        duration_delta: 135  # For the test to end, two blocks must occur within this range

        min_correct_answers: 2  # Number of correct answers in a row needed to continue with MP
        max_wrong_answers: 3  # Number of total wrong answers before the test ends

        no_response_duration: 6000  # No response time before the test ends

        max_block_count: 6  # Maximum number of blocks allowed before the test fails

    # The test slows down when the user gets less than `rolling_average.threshold` correct answers 
    slowdown:
        initial_duration: 100  # Ms slower than `self_paced_average` to start machine_paced
        base_duration: 100  # When slowing down, decrease `duration` by this amount

    # The test speeds up when the user gets more than `rolling_average.threshold` correct answers
    speedup:
        speedup_with_ratio_amount: 150 # Amount to speed up by * (ratio - `machine_paced.speedup.weighting`)
        weighting: 1.25  # Weighting of the ratio in the speedup calculation

anti_spoofing:
    max_bad_tests_in_session: 6 # Number of bad tests because retest is no longer an option

timeouts:
    max_initial_no_response: 10_000  # Initial starting time before the test ends if no response is given
    max_test_duration: 150_000  # Maximum time in milliseconds before the test ends
    
cpi_calculation:
    cpi_min: 0  # Lower bound
    cpi_max: 100  # Upper bound
    brd_min: 800  # Theoretical number where cpi should be 100
    brd_max: 2400  # Theoretical number where cpi should be 0

# Whether to save round data and have the ability for the user to download it - 
save_round_data: true  # Or to automatically send it to another user

number_of_endmode_rounds: 2  # Number of extra rounds at the end of the test

control: True  # A control variable that will always be true
