# All units in milliseconds unless otherwise specified
# CPI = Cognitive Performance Index - A score from 0-100
# BRD = Blocking Round Duration - Average time (in ms) between two blocks

# (^) = Implemented
# (?) = Unclear what this does

information_processing_rate:
    low: 0.5  # Minimum information processing rate
    high: 1.111  # Maximum information processing rate

self_paced:
    number_of_training_rounds: 2  # Number of rounds at the start to get the user used to the test ^
    max_wrong_count: 5  # Number of wrong answers before the test ends ^
    max_right_count: 4  # Number of right answers before self-paced test ends ^

machine_paced:
    max_count: 8  # ?
    max_start_duration: 2100  # Maximum initital `duration` (ignoring `self_paced_average`) ^
    not_there: 0  # ?
    not_there_disabled: true  # ?

    minimum_response_time: 500  # Theoretical minimum response time ^

    rolling_average:
        mean_size: 8  # Take the correct answers of the last `mean_size` rounds ^
        threshold: 0.6  # Percentage of correct answers before speeding up / slowing down ^

        max_wrong_count: 5  # Number of wrong answers before the test ends ^

    blocking:
        no_input_count: 2  # How many rounds with no response to declare a "block" ^
        self_paced_rounds: 2  # How many rounds to do after a block before resuming machine_paced ^

        slow_down_duration: 300  # After blocking, resume with `machine_pace` + this amount ^
        duration_delta: 135  # For the test to end, two blocks must occur within this range ^

    # The test slows down when the user gets less than `rolling_average.threshold` correct answers 
    slowdown:
        initial_duration: 75  # Ms slower than `self_paced_average` to start machine_paced ^
        base_duration: 100  # When slowing down, decrease `duration` by this amount ^

    # The test speeds up when the user gets more than `rolling_average.threshold` correct answers
    speedup:
        base_duration: 33  # When speeding up, decrease `duration` by this amount ^

anti_spoofing:
    max_bad_tests_in_session: 3  # Number of bad tests because retest is no longer an option

tutorial:  # ?
    tutorial_nSPRounds: 12
    tutorial_nMPRounds: 8
    tutorial_mpRoundStartDuration: 2100
    tutorial_mpRoundDurationDelta: -200

timeouts:
    max_initial_no_response: 10_000  # Initial starting time before the test ends if no response is given ^
    max_no_response: 5000  # Time before the test ends if no response is given ^
    max_test_duration: 120_000  # Maximum time in milliseconds before the test ends ^
    
cpi_calculation:
    cpi_min: 0  # Lower bound ^
    cpi_max: 100  # Upper bound ^
    brd_min: 800  # Theoretical number where cpi should be 100 ^
    brd_max: 2400  # Theoretical number where cpi should be 0 ^

# Whether to save round data and have the ability for the user to download it - 
save_round_data: true  # Or to automatically send it to another user

number_of_endmode_rounds: 2  # Number of extra rounds at the end of the test ^

mp_input_ends_round: true  # ?
mp_rt_buffer_size: 3  # ?

bpRoundCount: 3  # ?
n_inversecolordisplay: 3  # ?
p_displayother: 0.25  # ?
p_invert_letnum: 0.25  # ?