name: Push changelog links
on:
  workflow_run:
    workflows: ["Deploy to lambda"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Write to CHANGELOG.md
        run: |
          python scripts/write_changelog_links.py
          git config --global user.name github-actions
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: Push changes to CHANGELOG.md
        run: |
          git add CHANGELOG.md
          git commit -am "updating CHANGELOG.md" ||  true
          git push --force origin HEAD:$GITHUB_REF || true