name: Deploy to lambda
on:
  push:
    paths:
      - 'lambda_function.py'
      
jobs:

  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3

      - name: build requirements
        run: |
          pip install -r requirements.txt -t ./package

      - name: zip source code
        run: |
          cp ./lambda_function.py ./package
          cp ./config.yaml ./package
          cd package
          zip -r package.zip .

      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: getCogspeedConfig
          zip_file: ./package/package.zip